### ISSUE TITLE
为什么whisper总是识别出繁体，而且准确率很差

### ISSUE THREAD

**Issue by goactiongo** [morioka/tiny-openai-whisper-api#4]
本地部署的whisperapi，basic模型 small模型都一样

**Comment by morioka** [comment]
translated by Google-trasnlate:

"Why whisper always recognizes traditional characters, and the accuracy rate is very high"
"The on-premise whisper API, basic model, and small model are all the same"

Is this your question? 
I don't have an answer.   Probably, it should be discussed in [whisper](https://github.com/openai/whisper).
